package com.example.domain.strategy

import com.example.domain.model.*
import timber.log.Timber

data class EnsembleVote(
    val strategyType: StrategyType,
    val direction: TradeDirection?,
    val confidence: Double,
    val signal: Signal?,
    val weight: Double
)

data class EnsembleResult(
    val consensusDirection: TradeDirection?,
    val totalVotes: Int,
    val agreementRatio: Double,
    val weightedConfidence: Double,
    val votes: List<EnsembleVote>,
    val shouldExecute: Boolean,
    val reason: String
)

class StrategyEnsemble(
    private val strategies: Map<StrategyType, TradingStrategy>,
    private val minAgreementRatio: Double = 0.5,
    private val minWeightedConfidence: Double = 0.4
) {

    private val strategyPerformance = mutableMapOf<StrategyType, StrategyPerformance>()

    data class StrategyPerformance(
        var winRate: Double = 0.5,
        var totalTrades: Int = 0,
        var recentWins: Int = 0,
        var recentLosses: Int = 0,
        var weight: Double = 1.0
    )

    fun evaluate(
        candles: List<Candle>,
        symbolConfig: SymbolConfig,
        currentQuote: Quote,
        riskConfig: RiskConfig,
        hasOpenPosition: Boolean,
        lastProcessedCandleTime: Long,
        isConnectionHealthy: Boolean,
        dailyLossReached: Boolean,
        consecutiveLossesReached: Boolean,
        marginSufficient: Boolean
    ): EnsembleResult {
        val votes = mutableListOf<EnsembleVote>()

        for ((type, strategy) in strategies) {
            val weight = strategyPerformance[type]?.weight ?: 1.0

            val signal = strategy.evaluate(
                candles = candles,
                symbolConfig = symbolConfig,
                currentQuote = currentQuote,
                riskConfig = riskConfig,
                hasOpenPosition = hasOpenPosition,
                lastProcessedCandleTime = lastProcessedCandleTime,
                isConnectionHealthy = isConnectionHealthy,
                dailyLossReached = dailyLossReached,
                consecutiveLossesReached = consecutiveLossesReached,
                marginSufficient = marginSufficient
            )

            val vote = EnsembleVote(
                strategyType = type,
                direction = signal?.direction,
                confidence = if (signal != null) calculateSignalConfidence(signal) else 0.0,
                signal = signal,
                weight = weight
            )
            votes.add(vote)
        }

        return processVotes(votes)
    }

    private fun calculateSignalConfidence(signal: Signal): Double {
        var confidence = 0.5

        if (signal.rrRatio >= 2.0) confidence += 0.15
        else if (signal.rrRatio >= 1.5) confidence += 0.1

        if (signal.explanation.isAllPassed) confidence += 0.15

        val checksPassed = listOf(
            signal.explanation.trendCheck,
            signal.explanation.adxCheck,
            signal.explanation.pullbackCheck,
            signal.explanation.candleCheck,
            signal.explanation.spreadCheck,
            signal.explanation.riskCheck,
            signal.explanation.sessionCheck
        ).count { it }

        confidence += (checksPassed / 7.0) * 0.2

        return confidence.coerceIn(0.0, 1.0)
    }

    private fun processVotes(votes: List<EnsembleVote>): EnsembleResult {
        val buyVotes = votes.filter { it.direction == TradeDirection.BUY }
        val sellVotes = votes.filter { it.direction == TradeDirection.SELL }
        val abstentions = votes.filter { it.direction == null }

        val totalVotes = votes.size
        val activeVotes = totalVotes - abstentions.size

        if (activeVotes == 0) {
            return EnsembleResult(
                consensusDirection = null,
                totalVotes = totalVotes,
                agreementRatio = 0.0,
                weightedConfidence = 0.0,
                votes = votes,
                shouldExecute = false,
                reason = "No signals generated by any strategy"
            )
        }

        val buyWeight = buyVotes.sumOf { it.confidence * it.weight }
        val sellWeight = sellVotes.sumOf { it.confidence * it.weight }
        val totalWeight = votes.sumOf { it.confidence * it.weight }

        val consensusDirection = when {
            buyWeight > sellWeight && buyVotes.size > sellVotes.size -> TradeDirection.BUY
            sellWeight > buyWeight && sellVotes.size > buyVotes.size -> TradeDirection.SELL
            else -> null
        }

        val consensusVotes = when (consensusDirection) {
            TradeDirection.BUY -> buyVotes
            TradeDirection.SELL -> sellVotes
            else -> emptyList()
        }

        val agreementRatio = if (activeVotes > 0) {
            consensusVotes.size.toDouble() / activeVotes
        } else 0.0

        val weightedConfidence = if (totalWeight > 0) {
            when (consensusDirection) {
                TradeDirection.BUY -> buyWeight / totalWeight
                TradeDirection.SELL -> sellWeight / totalWeight
                else -> 0.0
            }
        } else 0.0

        val bestSignal = consensusVotes.maxByOrNull { it.confidence }?.signal

        val shouldExecute = consensusDirection != null &&
            agreementRatio >= minAgreementRatio &&
            weightedConfidence >= minWeightedConfidence &&
            bestSignal != null

        val reason = when {
            consensusDirection == null -> "No consensus direction"
            agreementRatio < minAgreementRatio -> "Insufficient agreement (${"%.1f".format(agreementRatio * 100)}% < ${"%.1f".format(minAgreementRatio * 100)}%)"
            weightedConfidence < minWeightedConfidence -> "Low weighted confidence (${"%.2f".format(weightedConfidence)} < $minWeightedConfidence)"
            !shouldExecute -> "Ensemble criteria not met"
            else -> "Ensemble consensus: ${consensusDirection.name} (${"%.1f".format(agreementRatio * 100)}% agreement, ${"%.2f".format(weightedConfidence)} confidence)"
        }

        Timber.d("Ensemble: $consensusDirection | Agreement: ${"%.1f".format(agreementRatio * 100)}% | Confidence: ${"%.2f".format(weightedConfidence)} | Execute: $shouldExecute")

        return EnsembleResult(
            consensusDirection = consensusDirection,
            totalVotes = totalVotes,
            agreementRatio = agreementRatio,
            weightedConfidence = weightedConfidence,
            votes = votes,
            shouldExecute = shouldExecute,
            reason = reason
        )
    }

    fun updatePerformance(strategyType: StrategyType, won: Boolean) {
        val perf = strategyPerformance.getOrPut(strategyType) { StrategyPerformance() }
        perf.totalTrades++
        if (won) perf.recentWins++ else perf.recentLosses++

        val recentTotal = perf.recentWins + perf.recentLosses
        if (recentTotal >= 10) {
            perf.winRate = perf.recentWins.toDouble() / recentTotal
            if (recentTotal >= 20) {
                perf.recentWins = (perf.recentWins * 0.8).toInt()
                perf.recentLosses = (perf.recentLosses * 0.8).toInt()
            }
        }

        perf.weight = (perf.winRate * 1.5).coerceIn(0.3, 2.0)
    }

    fun getStrategyWeights(): Map<StrategyType, Double> {
        return strategyPerformance.mapValues { it.value.weight }
    }
}
